### ISSUE TITLE
Cannot add a MAX! thermostatic radiator valve

### ISSUE THREAD

**Issue by theeuwke** [meyerd/pimatic-homegear#1]
Nothing is listed in debug log (no devices), while a devices is registered in homegear as family 4 device id 1. So I added a device manually; 

  "devices": [
    {
      "id": "bathroomLeft",
      "class": "HomematicHeatingThermostat",
      "name": "Bathroom Radiator left",
      "peerID": 1,
      "channel": 4,
      "comfyTemp": 23.0,
      "ecoTemp": 17.5,
    },
    {
      "id": "temperatureBathroomLeft",
      "class": "HomematicThermostat",
      "name": "Bathroom Temperature Radiator left",
      "peerID": 1,
      "channel": 4,
    }
  ],

Should I use an other "class" with MAX! valves? 

with peerID 1 and channel 4. Now I get this error:

16:07:25.603 [pimatic-homegear] debug: setTemperatureSetpoint 1 4 auto 16.5
16:07:25.735 [pimatic-homegear] error: error setting auto mode for peer 1
16:07:25.798 [pimatic-homegear] debug: Error: XML-RPC fault: Unknown channel.
16:07:25.798 [pimatic-homegear] debug:>    at createFault (/home/pi/pimatic-app/node_modules/pimatic-homegear/node_modules/homematic-xmlrpc/lib/deserializer.js:83:21)
16:07:25.798 [pimatic-homegear] debug:>    at Deserializer.onDone (/home/pi/pimatic-app/node_modules/pimatic-homegear/node_modules/homematic-xmlrpc/lib/deserializer.js:89:21)
16:07:25.798 [pimatic-homegear] debug:>    at SAXStream.EventEmitter.emit (events.js:92:17)
16:07:25.798 [pimatic-homegear] debug:>    at Object.SAXStream._parser.onend (/home/pi/pimatic-app/node_modules/pimatic-homegear/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:171:8)
16:07:25.798 [pimatic-homegear] debug:>    at emit (/home/pi/pimatic-app/node_modules/pimatic-homegear/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:325:33)
16:07:25.798 [pimatic-homegear] debug:>    at end (/home/pi/pimatic-app/node_modules/pimatic-homegear/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:363:3)
16:07:25.798 [pimatic-homegear] debug:>    at Object.SAXParser.end (/home/pi/pimatic-app/node_modules/pimatic-homegear/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:137:24)
16:07:25.798 [pimatic-homegear] debug:>    at SAXStream.end (/home/pi/pimatic-app/node_modules/pimatic-homegear/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:209:16)
16:07:25.798 [pimatic-homegear] debug:>    at IncomingMessage.onend (_stream_readable.js:483:10)
16:07:25.798 [pimatic-homegear] debug:>    at IncomingMessage.g (events.js:180:16)
16:07:25.798 [pimatic-homegear] debug:>    at IncomingMessage.EventEmitter.emit (events.js:117:20)
16:07:25.798 [pimatic-homegear] debug:>    at _stream_readable.js:920:16
16:07:25.798 [pimatic-homegear] debug:>    at process._tickCallback (node.js:415:13)
16:07:34.480 [pimatic-homegear] debug: setTemperatureSetpoint 1 4 auto 20
16:07:34.583 [pimatic-homegear] error: error setting auto mode for peer 1
16:07:34.639 [pimatic-homegear] debug: Error: XML-RPC fault: Unknown channel.

**Comment by theeuwke** [comment]
fixed the issue by manually get the peerid/channel from homegear rpc.
